### ISSUE TITLE
Universal + Text-Based Fountain

### ISSUE THREAD

**Issue by apatzer** [askdavinci/marketing#17]
Top level issue for publicly launching Fountain across all categories of knowledge + a text-first/SMS interface (anticipated to launch together as one announcement).

**Distribution**
* [ ] _P1_ Sign-up experts in new verticals

**Web Changes**
* [ ] New homepage askdavinci/expert#2161

**Email Communication**
* [ ] _P2_ Rewrite all Pardot emails for "ask anything" Fountain
* [ ] _P2_ Email existing users for trial of Universal Fountain

**Press**
* [ ] _P1_ Messaging: Universal + Text-Based Fountain #7  
* [ ] _P2_ PR: Free veterinary, legal, medical or other key category to everyone in June.

**Video Content**
* [ ] _P3_ Product video: help on anything, legal to medical, home improvement to tech help and tutoring.
