### ISSUE TITLE
Web + Distributed Fountain

### ISSUE THREAD

**Issue by apatzer** [askdavinci/marketing#8]
Top level issue for publicly launching the web version of Fountain, plus the "distributed" Fountain.com/UserName platform.

**Distribution**
* [ ] _P1_ Trials with: Stylist, Vet & Contractor
* [ ] _P2_ Sign up 50-100 YouTube home & garden experts to trial the system
* [ ] _P3_ Sign up 50-100 Twitter experts across a wide variety of categories

**Web Changes**
* [ ] Make becoming an expert a 3-minute process https://github.com/askdavinci/expert/issues/2221

**Email Communication**
* [ ] _P1_ Email existing experts with default usernames & rates
* [ ] _P2_ Email Google Helpouts experts to transition their business by April 20th

**Press**
* [ ] _P1_ Messaging: Web + Distributed #6 

**Video Content**
* [ ] _P3_ How-to video: Using Fountain.com/UserName on YouTube, Twitter, and in Email
